// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedcaloriescolumninworkoutandentries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcaloriescolumninworkoutandentries));
        
        string IMigrationMetadata.Id
        {
            get { return "201906130456185_added calories column in workout and entries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
